'use strict';

const { createSafeError } = require('../safe-errors');

const POLICY_SOURCE_ERROR_CODES = Object.freeze({
  POLICY_SOURCE_BINDING_INVALID: 'POLICY_SOURCE_BINDING_INVALID',
  POLICY_RPC_CHAIN_MISMATCH: 'POLICY_RPC_CHAIN_MISMATCH',
  POLICY_RPC_READ_FAILED: 'POLICY_RPC_READ_FAILED',
  POLICY_ABI_DECODE_FAILED: 'POLICY_ABI_DECODE_FAILED',
  POLICY_SCHEMA_INVALID: 'POLICY_SCHEMA_INVALID',
  POLICY_VERSION_UNSUPPORTED: 'POLICY_VERSION_UNSUPPORTED',
  POLICY_CONTRACT_STALE_OR_DEAD: 'POLICY_CONTRACT_STALE_OR_DEAD',
  POLICY_FROZEN: 'POLICY_FROZEN',
});

function policySourceError(code, safeDetails = {}) {
  return createSafeError(code, { safeDetails });
}

module.exports = {
  POLICY_SOURCE_ERROR_CODES,
  policySourceError,
};
